version: "3.8"
services:
  backend:
    container_name: nodejsv19
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
      - /app/node_modules